github: @FabianaCampanari
['https://github.com/FabianaCampanari',
'https://github.com/FabianaCampanari/University-Python-Projects']
open_collective: @FabianaCampanari
['https://opencollective.com/fabianacampanari',
'https://opencollective.com/fabianacampanari/projects/university-python-projects']
