github: @FabianaCampanari
['https://github.com/FabianaCampanari']
open_collective: @FabianaCampanari
['https://opencollective.com/fabianacampanari',
'https://opencollective.com/fabianacampanari/projects/university-python-projects']
